name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

permissions:
  contents: write  # Give write permissions to contents to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --configuration Release --runtime ${{ matrix.rid }} --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./output

    - name: Archive output (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: vma-comparer-${{ matrix.rid }}
        path: ./output/*.exe
        if-no-files-found: error

    - name: Archive output (Non-Windows)
      if: matrix.os != 'windows-latest'
      run: tar -czvf vma-comparer-${{ matrix.rid }}.tar.gz -C ./output .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: matrix.os != 'windows-latest'
      with:
        name: vma-comparer-${{ matrix.rid }}
        path: vma-comparer-${{ matrix.rid }}.${{ matrix.ext }}
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: vma-comparer-linux-x64
        path: ./artifacts/linux-x64

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: vma-comparer-win-x64
        path: ./artifacts/win-x64

    - name: Download macOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: vma-comparer-osx-x64
        path: ./artifacts/osx-x64

    - name: Create GitHub Release
      uses: ghalactic/github-release-from-tag@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        assets: |
          - path: ./artifacts/linux-x64/vma-comparer-linux-x64.tar.gz
            name: vma-comparer-linux-x64.tar.gz
          - path: ./artifacts/win-x64/vma-comparer-win-x64.zip
            name: vma-comparer-win-x64.zip
          - path: ./artifacts/osx-x64/vma-comparer-osx-x64.tar.gz
            name: vma-comparer-osx-x64.tar.gz